// src/lib/activities.js
export const activities = [
    {
      id: 1,
      slug: "5-seen-fahrt-bad-malente",
      title: "5-Seen-Fahrt Bad Malente",
      category: "Natur & Schifffahrt",
      lat: 54.172,
      lng: 10.556,
      description:
        "Beliebte Schifffahrt durch die Seenlandschaft der Holsteinischen Schweiz – entspannt, familienfreundlich und mit tollen Ausblicken.",
      content:
        "Die 5-Seen-Fahrt gehört zu den Klassikern in der Holsteinischen Schweiz. Auf dem Wasser erlebst du die Region besonders ruhig und eindrucksvoll. Ideal als Halbtagesausflug – auch perfekt, wenn du einfach mal abschalten möchtest.",
      tips: ["Früh da sein in der Hauptsaison", "Windjacke mitnehmen", "Kombi mit Malente-Spaziergang"],
      website: "",
      address: "Bad Malente (Anleger je nach Route)",
      image: "/activities/5-seen-fahrt.jpg",
    },
    {
      id: 2,
      slug: "powerpark-gluecksburg",
      title: "POWERPARK Glücksburg",
      category: "Freizeitpark",
      lat: 54.822,
      lng: 9.548,
      description:
        "Outdoor-Freizeitpark mit Action- und Spielangeboten – ideal für Familien und Gruppen.",
      content:
        "Im POWERPARK geht’s um Bewegung, Spaß und gemeinsame Erlebnisse. Perfekt für einen aktiven Tagesausflug – besonders wenn Kinder oder eine Gruppe dabei sind.",
      tips: ["Bequeme Schuhe", "Snack & Wasser einpacken", "Wetter checken"],
      website: "",
      address: "Glücksburg (Schleswig-Flensburg)",
      image: "/activities/powerpark.jpg",
    },
    {
      id: 3,
      slug: "barfusspark-schwackendorf",
      title: "Barfusspark Schwackendorf",
      category: "Natur & Familie",
      lat: 54.494,
      lng: 9.913,
      description:
        "Barfußpfade, Naturstationen und spielerische Elemente – ein besonderes Erlebnis für Groß & Klein.",
      content:
        "Der Barfußpark ist ein ruhiger, naturnaher Ausflug – ideal für Familien. Unterschiedliche Untergründe, Stationen und kleine Herausforderungen machen’s abwechslungsreich.",
      tips: ["Handtuch mitnehmen", "Für Kinder Wechselkleidung", "Zeit fürs Entspannen einplanen"],
      website: "",
      address: "Schwackendorf (Schleswig-Holstein)",
      image: "/activities/barfusspark.jpg",
    },
    {
      id: 4,
      slug: "bonbonkocherei-eckernfoerde",
      title: "Bonbonkocherei Eckernförde",
      category: "Manufaktur",
      lat: 54.474,
      lng: 9.839,
      description:
        "Süßes Handwerk live erleben: Bonbons werden vor Ort gekocht, geformt und verpackt – inkl. Probieren & Shop.",
      content:
        "Ein kurzer, aber sehr beliebter Stopp in Eckernförde: In der Bonbonkocherei schaust du bei der Herstellung zu und findest tolle Mitbringsel. Perfekt bei jedem Wetter.",
      tips: ["Als Stop mit Hafen/Altstadt kombinieren", "Für Kinder mega", "Günstiges Mitbringsel"],
      website: "",
      address: "Eckernförde",
      image: "/activities/bonbonkocherei.jpg",
    },
    {
      id: 5,
      slug: "botanischer-garten-kiel",
      title: "Botanischer Garten Kiel",
      category: "Natur",
      lat: 54.345,
      lng: 10.122,
      description:
        "Weitläufiger botanischer Garten mit Pflanzen aus aller Welt, Gewächshäusern und ruhigen Spazierwegen.",
      content:
        "Perfekt für einen entspannten Spaziergang – besonders, wenn du Natur und schöne Fotospots magst. Auch bei wechselhaftem Wetter lohnend durch Gewächshäuser.",
      tips: ["Kamera/Handy laden", "Ruhige Zeiten vormittags", "Kombi mit Kiel-Ausflug"],
      website: "",
      address: "Kiel",
      image: "/activities/botanischer-garten-kiel.jpg",
    },
    {
      id: 6,
      slug: "der-lutterbeker",
      title: "Der Lutterbeker",
      category: "Kultur & Genuss",
      lat: 54.397,
      lng: 10.224,
      description:
        "Kleinkunst, Kultur & gemütlicher Treffpunkt – bekannt für Veranstaltungen, Atmosphäre und gutes Essen.",
      content:
        "Der Lutterbeker ist ein besonderer Ort für einen Abend mit Kultur oder entspanntem Essen. Je nach Programm gibt’s Kleinkunst, Musik oder Events.",
      tips: ["Programm vorher checken", "Reservierung sinnvoll", "Abends besonders schön"],
      website: "",
      address: "Lutterbek (bei Laboe)",
      image: "/activities/lutterbeker.jpg",
    },
    {
      id: 7,
      slug: "luebecker-marzipan-speicher",
      title: "Lübecker Marzipan-Speicher",
      category: "Kulinarik",
      lat: 53.868,
      lng: 10.686,
      description:
        "Marzipan-Erlebnis in Lübeck: Geschichte, Genuss und Shop – ideal als Ergänzung zur Altstadt.",
      content:
        "Wenn du Lübeck besuchst, gehört Marzipan irgendwie dazu. Der Marzipan-Speicher ist eine tolle Station für Genießer und als Mitbringsel-Stop.",
      tips: ["Mit Altstadt kombinieren", "Für Regentage ideal", "Souvenir/Präsent einplanen"],
      website: "",
      address: "Lübeck",
      image: "/activities/marzipan-speicher.jpg",
    },
    {
      id: 8,
      slug: "eisstockschiessen-palmengarten-kiel",
      title: "Eisstockschießen im Palmengarten (Kiel)",
      category: "Freizeit",
      lat: 54.324,
      lng: 10.135,
      description:
        "Winterspaß in Kiel: Eisstockbahn im Palmengarten – perfekt für Gruppen, Freunde und Familie.",
      content:
        "Ein toller Programmpunkt in der kühleren Jahreszeit: Eisstockschießen macht Spaß, ist schnell gelernt und ideal als Gruppenerlebnis.",
      tips: ["Warm anziehen", "Vorher reservieren (saisonal)", "Mit Essen/Drink kombinieren"],
      website: "",
      address: "Kiel",
      image: "/activities/eisstock-kiel.jpg",
    },
    {
      id: 9,
      slug: "erlebniswald-trappenkamp",
      title: "Erlebniswald Trappenkamp",
      category: "Natur & Familie",
      lat: 54.065,
      lng: 10.204,
      description:
        "Erlebniswald mit Spiel- und Lernstationen, Tiergehegen und viel Platz zum Toben – super Familienausflug.",
      content:
        "Ein Klassiker für Familien: Natur erleben, spielen, entdecken und zwischendurch entspannen. Ideal für einen halben oder ganzen Tag.",
      tips: ["Picknick möglich", "Für Kinderwagen je nach Wegeplanung", "Wechselkleidung für Kids"],
      website: "",
      address: "Trappenkamp",
      image: "/activities/erlebniswald-trappenkamp.jpg",
    },
    {
      id: 10,
      slug: "esel-und-landspielhof-nessendorf",
      title: "Esel- & Landspielhof Nessendorf",
      category: "Familie & Tiere",
      lat: 54.244,
      lng: 10.770,
      description:
        "Familienpark mit Tieren, Indoor-Spielbereich und vielen Outdoor-Stationen – ideal bei jedem Wetter.",
      content:
        "Hier haben Kinder richtig viel zu tun: Tiere, Spielbereiche und oft auch wetterfeste Optionen. Perfekt für Familien mit kleineren Kindern.",
      tips: ["Für Regentage geeignet", "Zeit einplanen (Kinder wollen bleiben)", "Snacks/Trinken dabei"],
      website: "",
      address: "Nessendorf (Ostholstein)",
      image: "/activities/nessendorf.jpg",
    },
    {
      id: 11,
      slug: "field-und-fun-kluetz",
      title: "field & fun (Klütz)",
      category: "Freizeit",
      lat: 53.963,
      lng: 11.161,
      description:
        "Aktiver Freizeitspaß: Outdoor-Angebote und Spielmöglichkeiten – gut für Familien und Gruppen.",
      content:
        "Ein Ziel für alle, die Action draußen mögen. Je nach Saison gibt es unterschiedliche Angebote – perfekt als Tagesausflug in der Umgebung.",
      tips: ["Wetter checken", "Bequeme Kleidung", "Als Gruppen-Ausflug top"],
      website: "",
      address: "Klütz",
      image: "/activities/field-fun.jpg",
    },
    {
      id: 12,
      slug: "flensburger-brauerei",
      title: "Flensburger Brauerei",
      category: "Brauerei & Kultur",
      lat: 54.783,
      lng: 9.435,
      description:
        "Brauereiführung und Genuss: Einblicke in die Herstellung und (je nach Angebot) Verkostung.",
      content:
        "Für Bierfans ein Muss: Flensburger ist Kult. In der Führung bekommst du Hintergrund, Geschichte und Brauerei-Feeling.",
      tips: ["Tickets/Zeiten prüfen", "Mit Flensburg-Städtetrip kombinieren", "Fahrer*in einplanen"],
      website: "",
      address: "Flensburg",
      image: "/activities/flensburger-brauerei.jpg",
    },
    {
      id: 13,
      slug: "galileo-wissenswelt-fehmarn",
      title: "Galileo Wissenswelt (Fehmarn)",
      category: "Museum & Familie",
      lat: 54.438,
      lng: 11.192,
      description:
        "Interaktive Wissenswelt – spannend für Kinder und Erwachsene, besonders bei schlechtem Wetter.",
      content:
        "Entdecken, ausprobieren, lernen: Die Galileo Wissenswelt bietet abwechslungsreiche Stationen und Themen – ideal für Familienausflüge.",
      tips: ["Perfekt bei Regen", "Zeit für Mitmachstationen einplanen", "Mit Fehmarn-Ausflug kombinieren"],
      website: "",
      address: "Fehmarn",
      image: "/activities/galileo-fehmarn.jpg",
    },
    {
      id: 14,
      slug: "wildpark-schwentinetal",
      title: "Wildpark Schwentinental",
      category: "Natur & Tiere",
      lat: 54.285,
      lng: 10.223,
      description:
        "Kleiner Wildpark mit heimischen Tieren und Spazierwegen – entspannt und oft kostenlos zugänglich.",
      content:
        "Ein ruhiger, naturnaher Ausflug – ideal für eine kleine Runde, wenn du Tiere sehen und draußen sein willst.",
      tips: ["Kurzer Ausflug möglich", "Für Kinder super", "Wetterfeste Schuhe"],
      website: "",
      address: "Schwentinental",
      image: "/activities/wildpark-schwentinetal.jpg",
    },
    {
      id: 15,
      slug: "geocaching-kiel",
      title: "Geocaching (Kiel & Umgebung)",
      category: "Outdoor",
      lat: 54.323,
      lng: 10.122,
      description:
        "GPS-Schatzsuche in Kiel und Umgebung – perfekt für Abenteurer, Familien und Teamevents.",
      content:
        "Geocaching ist wie eine moderne Schatzsuche. Du brauchst nur Handy/GPS und Lust, draußen Rätsel zu lösen – super für alle Altersgruppen.",
      tips: ["Powerbank mitnehmen", "Mit Kindern sehr beliebt", "Routen vorher speichern"],
      website: "",
      address: "Kiel & Umgebung",
      image: "/activities/geocaching.jpg",
    },
    {
      id: 16,
      slug: "grosse-ploener-see-rundfahrt",
      title: "Große Plöner See-Rundfahrt",
      category: "Natur & Schifffahrt",
      lat: 54.160,
      lng: 10.420,
      description:
        "Ruhige Bootsrundfahrt auf dem Großen Plöner See – Naturpanorama, entspannt und fotogen.",
      content:
        "Perfekt für einen entspannten Tag in der Holsteinischen Schweiz. Auf dem Wasser wirkt die Landschaft besonders beeindruckend.",
      tips: ["Windjacke", "Kamera/Handy", "Mit Plön/Schloss kombinieren"],
      website: "",
      address: "Plön",
      image: "/activities/ploener-see.jpg",
    },
    {
      id: 17,
      slug: "gut-panker",
      title: "Gut Panker",
      category: "Kultur & Gutshof",
      lat: 54.332,
      lng: 10.576,
      description:
        "Historisches Gut mit Galerien, kleinen Shops und Cafés – ideal für einen ruhigen Ausflug.",
      content:
        "Gut Panker bietet eine besondere Atmosphäre: Kultur, kleine Manufakturen und entspanntes Flanieren in schöner Umgebung.",
      tips: ["Zeit für Café einplanen", "Schöner Fotospot", "Ruhig unter der Woche"],
      website: "",
      address: "Panker",
      image: "/activities/gut-panker.jpg",
    },
    {
      id: 18,
      slug: "hansapark-sierksdorf",
      title: "Hansapark Sierksdorf",
      category: "Freizeitpark",
      lat: 54.074,
      lng: 10.780,
      description:
        "Großer Freizeitpark an der Ostsee mit Achterbahnen, Themenwelten und Shows – perfekt für Familien & Action-Fans.",
      content:
        "Der Hansa-Park ist eines der bekanntesten Ausflugsziele an der Ostsee. Neben Achterbahnen gibt es Familienattraktionen, Shows und Themenbereiche – ideal für einen ganzen Tag.",
      tips: ["Tickets online prüfen", "Früh da sein", "Für Regen: Shows/Indoor-Angebote"],
      website: "https://www.hansapark.de",
      address: "Sierksdorf",
      image: "/activities/hansapark.jpg",
    },
    {
      id: 19,
      slug: "irrgarten-und-minigolf-probsteierhagen",
      title: "Irrgarten & Minigolf Probsteierhagen",
      category: "Familie",
      lat: 54.363,
      lng: 10.288,
      description:
        "Labyrinthspaß und Minigolf – ein lockerer Ausflug für Familien, Paare und Gruppen.",
      content:
        "Ein schöner, unkomplizierter Ausflug: erst durch den Irrgarten, danach eine Runde Minigolf. Perfekt für 2–3 Stunden.",
      tips: ["Ideal am Nachmittag", "Mit Café/Region kombinieren", "Für alle Altersgruppen"],
      website: "",
      address: "Probsteierhagen",
      image: "/activities/irrgarten-probsteierhagen.jpg",
    },
    {
      id: 20,
      slug: "jumpy-doo-fehmarn",
      title: "Jumpy-Doo – Die Spielfabrik (Fehmarn)",
      category: "Indoor-Spielpark",
      lat: 54.435,
      lng: 11.193,
      description:
        "Indoor-Spielpark mit viel Bewegung und Spaß – perfekt bei Regen und für kleinere Kinder.",
      content:
        "Wenn das Wetter nicht mitspielt, ist Jumpy-Doo ein echter Rettungsanker. Hüpf- und Spielbereiche sorgen für Action – Eltern können entspannter mitlaufen.",
      tips: ["Perfekt bei Regen", "Socken/Wechselkleidung", "Unter der Woche entspannter"],
      website: "",
      address: "Fehmarn",
      image: "/activities/jumpy-doo.jpg",
    },
    {
      id: 21,
      slug: "karl-may-spiele-bad-segeberg",
      title: "Karl-May-Spiele Bad Segeberg",
      category: "Kultur",
      lat: 53.944,
      lng: 10.309,
      description:
        "Open-Air-Klassiker in Bad Segeberg: spektakuläre Inszenierungen, Stunts und echte Sommer-Event-Atmosphäre.",
      content:
        "Die Karl-May-Spiele sind ein Highlight im Sommer. Große Bühne, Action und besondere Atmosphäre – ideal als Abendprogramm mit Familie oder Freunden.",
      tips: ["Tickets früh sichern", "Abends Jacke mitnehmen", "Früh anreisen (Parken)"],
      website: "",
      address: "Bad Segeberg",
      image: "/activities/karl-may.jpg",
    },
    {
      id: 22,
      slug: "kerzenscheune-krummbek",
      title: "Kerzenscheune Krummbek",
      category: "Manufaktur",
      lat: 54.361,
      lng: 10.378,
      description:
        "Kerzenmanufaktur mit Shop – schönes Ziel für Deko, Geschenkideen und einen kurzen Ausflug.",
      content:
        "In der Kerzenscheune findest du viele Designs und saisonale Highlights. Ideal als kurzer Zwischenstopp, auch bei schlechtem Wetter.",
      tips: ["Als Stop kombinieren", "Saisonware (Weihnachten/Ostern)", "Mit Café verbinden"],
      website: "",
      address: "Krummbek",
      image: "/activities/kerzenscheune.jpg",
    },
    {
      id: 23,
      slug: "mare-wellness-und-sport-schoenkirchen",
      title: "MARE Wellness & Sport (Schönkirchen)",
      category: "Sport & Wellness",
      lat: 54.333,
      lng: 10.217,
      description:
        "Fitness, Kurse und Wellness-Angebote – gut als Schlechtwetter-Alternative oder für aktive Urlaubstage.",
      content:
        "Wenn du im Urlaub aktiv bleiben möchtest oder Wellness suchst, ist MARE eine solide Option. Je nach Angebot gibt es Kurse, Training und Erholung.",
      tips: ["Zeiten/Angebote prüfen", "Handtuch dabei", "Ideal bei Regen"],
      website: "",
      address: "Schönkirchen",
      image: "/activities/mare-schoenkirchen.jpg",
    },
    {
      id: 24,
      slug: "mediendom-kiel",
      title: "Mediendom Kiel",
      category: "Bildung & Planetarium",
      lat: 54.323,
      lng: 10.137,
      description:
        "360°-Kuppel mit Shows, Wissenschaft und Planetarium-Feeling – beeindruckend für jedes Alter.",
      content:
        "Der Mediendom ist ein echtes Erlebnis: Rundum-Projektionen schaffen eine besondere Atmosphäre. Perfekt für Familien und als Schlechtwetter-Programm.",
      tips: ["Showzeiten checken", "Perfekt bei Regen", "Mit Kiel-Ausflug kombinieren"],
      website: "",
      address: "Kiel",
      image: "/activities/mediendom-kiel.jpg",
    },
    {
      id: 25,
      slug: "meeresbiologische-station-laboe",
      title: "Meeresbiologische Station Laboe",
      category: "Natur & Aquarium",
      lat: 54.405,
      lng: 10.224,
      description:
        "Kleine Aquarienanlage mit Fokus Ostsee – ideal als kurzer Stopp, besonders mit Kindern.",
      content:
        "Ein schöner Zwischenstopp in Laboe: Du bekommst Einblicke in die Ostsee-Unterwasserwelt – kompakt, informativ und familienfreundlich.",
      tips: ["Mit Laboe/Strand kombinieren", "Ideal für 1–2 Stunden", "Perfekt bei Regen"],
      website: "",
      address: "Laboe",
      image: "/activities/meeresbiologie-laboe.jpg",
    },
    {
      id: 26,
      slug: "meereszentrum-fehmarn",
      title: "Meereszentrum Fehmarn",
      category: "Aquarium",
      lat: 54.438,
      lng: 11.193,
      description:
        "Großes Aquarium mit Haien, Tropenfischen und Korallenriffen – eines der beliebtesten Indoor-Ziele auf Fehmarn.",
      content:
        "Das Meereszentrum ist perfekt bei Regen oder Wind. Besonders die Haibecken sind ein Highlight. Ideal für Familien, aber auch für Paare spannend.",
      tips: ["Perfekt bei Regen", "Unter der Woche ruhiger", "Mit Fehmarn-Trip kombinieren"],
      website: "",
      address: "Fehmarn",
      image: "/activities/meereszentrum.jpg",
    },
    {
      id: 27,
      slug: "nabu-wasservogelreservat-wallnau",
      title: "NABU Wasservogelreservat Wallnau",
      category: "Natur",
      lat: 54.480,
      lng: 11.040,
      description:
        "Naturschutzgebiet auf Fehmarn mit Beobachtungsstationen – ein Paradies für Natur- und Vogelfans.",
      content:
        "Wallnau ist ideal, wenn du Natur liebst: Aussichtspunkte, Beobachtungen und ruhige Wege. Besonders zur Zugzeit beeindruckend.",
      tips: ["Fernglas mitnehmen", "Morgens oft am besten", "Windschutz einpacken"],
      website: "",
      address: "Fehmarn",
      image: "/activities/wallnau.jpg",
    },
    {
      id: 28,
      slug: "naturerleben-achterwehr",
      title: "Naturerleben Achterwehr",
      category: "Natur",
      lat: 54.308,
      lng: 9.948,
      description:
        "Natur- und Umweltangebote – gut für Familien, Kinder und alle, die draußen etwas entdecken möchten.",
      content:
        "Ein ruhiger Ausflug in die Natur. Je nach Angebot gibt es Stationen und Themen rund um Umwelt und regionale Natur.",
      tips: ["Wetterfeste Schuhe", "Mit Kanal-/Radtour kombinieren", "Ruhiger als große Attraktionen"],
      website: "",
      address: "Achterwehr",
      image: "/activities/achterwehr.jpg",
    },
    {
      id: 29,
      slug: "natuerlich-reiten-stakendorf",
      title: "Natürlich Reiten (Stakendorf)",
      category: "Reitsport",
      lat: 54.393,
      lng: 10.386,
      description:
        "Reiten an der Ostsee – Kurse und Ausritte, je nach Angebot auch für Einsteiger.",
      content:
        "Reiten ist eine wunderschöne Möglichkeit, die Region zu erleben. Ideal für Reitfans – bitte vorher Angebot und Voraussetzungen klären.",
      tips: ["Vorab buchen", "Kleidung passend wählen", "Für Kinder: Angebote prüfen"],
      website: "",
      address: "Stakendorf",
      image: "/activities/reiten-stakendorf.jpg",
    },
    {
      id: 30,
      slug: "obst-erlebnis-garten-blekendorf",
      title: "Obst-Erlebnis-Garten (Blekendorf)",
      category: "Familie & Natur",
      lat: 54.288,
      lng: 10.645,
      description:
        "Erlebnisgarten rund ums Obst – Hofladen, Natur und je nach Saison tolle Aktionen für Familien.",
      content:
        "Ein schöner, regionaler Ausflug: Natur, Hofladen und je nach Saison unterschiedliche Angebote. Perfekt für einen ruhigen Nachmittag.",
      tips: ["Saisonangebote checken", "Mit Strandtag kombinieren", "Hofladen nicht vergessen"],
      website: "",
      address: "Blekendorf",
      image: "/activities/obst-garten.jpg",
    },
    {
      id: 31,
      slug: "ostsee-erlebniswelt-heiligenhafen",
      title: "Ostsee Erlebniswelt Heiligenhafen",
      category: "Familie & Museum",
      lat: 54.374,
      lng: 10.987,
      description:
        "Interaktive Ausstellung rund um Meer, Küste und Fischerei – ideal für Familien und Schlechtwettertage.",
      content:
        "Die Ostsee Erlebniswelt ist ein Indoor-Ziel mit viel Wissen und Erlebnis. Ideal als Programmpunkt bei Regen oder Wind.",
      tips: ["Perfekt bei Regen", "Mit Heiligenhafen kombinieren", "Zeit fürs Entdecken"],
      website: "",
      address: "Heiligenhafen",
      image: "/activities/erlebniswelt-heiligenhafen.jpg",
    },
    {
      id: 32,
      slug: "ostsee-therme-scharbeutz",
      title: "Ostsee-Therme Scharbeutz",
      category: "Wellness",
      lat: 54.023,
      lng: 10.754,
      description:
        "Großes Erlebnisbad mit Rutschen, Saunen und Wellness – perfekte Schlechtwetter-Alternative.",
      content:
        "Die Ostsee-Therme ist ideal für einen Wellness-Tag oder Familienausflug. Rutschen, Becken und Sauna machen sie zu einem Top-Ziel.",
      tips: ["Handtuch/Bademantel", "Unter der Woche entspannter", "Sauna-Bereich für Erwachsene"],
      website: "",
      address: "Scharbeutz",
      image: "/activities/ostsee-therme.jpg",
    },
    {
      id: 33,
      slug: "ostseereitschule-luett-piergorn",
      title: "Ostseereitschule Lütt Piergorn",
      category: "Reitsport",
      lat: 54.349,
      lng: 10.471,
      description:
        "Reitschule nahe der Ostsee – Kurse, Unterricht und Ausritte, je nach Angebot auch für Anfänger.",
      content:
        "Ein schönes Angebot für Reitfans. Bitte vorab klären, welche Kurse/Ausritte verfügbar sind und ob Vorerfahrung nötig ist.",
      tips: ["Vorab buchen", "Wetter/Outfit beachten", "Für Kinder Angebote prüfen"],
      website: "",
      address: "Region Probstei (nahe Ostsee)",
      image: "/activities/luett-piergorn.jpg",
    },
    {
      id: 34,
      slug: "phaenomenta-flensburg",
      title: "Phänomenta Flensburg",
      category: "Science Center",
      lat: 54.790,
      lng: 9.434,
      description:
        "Mitmachmuseum mit Experimenten und Aha-Momenten – super für Familien, Jugendliche und neugierige Erwachsene.",
      content:
        "Hier darfst du alles ausprobieren: Physik, Wahrnehmung und spannende Experimente. Perfekt bei Regen und als Tagesausflug nach Flensburg.",
      tips: ["Perfekt bei Regen", "Zeit für Experimente einplanen", "Mit Flensburg kombinieren"],
      website: "",
      address: "Flensburg",
      image: "/activities/phaenomenta.jpg",
    },
    {
      id: 35,
      slug: "piratenlager-hohwacht",
      title: "Piratenlager Hohwacht",
      category: "Familie",
      lat: 54.324,
      lng: 10.668,
      description:
        "Abenteuerprogramm für Kinder – Piratenaktionen, Spiel und Strand-Feeling in der Saison.",
      content:
        "Ein Highlight für Familien: Kinder können spielerisch in Piratenwelten eintauchen. Ideal als Ergänzung zum Strandtag.",
      tips: ["Saisonzeiten prüfen", "Wechselkleidung", "Mit Strandtag kombinieren"],
      website: "",
      address: "Hohwacht",
      image: "/activities/piratenlager.jpg",
    },
    {
      id: 36,
      slug: "eiszeitmuseum-luetjenburg",
      title: "Schleswig-Holsteinisches Eiszeitmuseum (Lütjenburg)",
      category: "Museum",
      lat: 54.291,
      lng: 10.586,
      description:
        "Spannendes Museum zur Eiszeitgeschichte und Landschaftsentwicklung in Schleswig-Holstein.",
      content:
        "Ein ideales Ziel für alle, die gern verstehen, wie die Region entstanden ist. Gut kombinierbar mit einem Ausflug nach Lütjenburg.",
      tips: ["Perfekt bei Regen", "Mit Stadtbummel kombinieren", "Für interessierte Kids super"],
      website: "",
      address: "Lütjenburg",
      image: "/activities/eiszeitmuseum.jpg",
    },
    {
      id: 37,
      slug: "schmetterlingspark-burg-fehmarn",
      title: "Schmetterlingspark Burg (Fehmarn)",
      category: "Natur",
      lat: 54.435,
      lng: 11.193,
      description:
        "Tropenhalle mit frei fliegenden Schmetterlingen – ein besonderes Erlebnis für Familien und Naturfans.",
      content:
        "Warm, tropisch und voller Farben: Ein tolles Indoor-Ziel auf Fehmarn – besonders schön für Kinder und Fotofans.",
      tips: ["Perfekt bei Regen", "Kamera/Handy", "Mit Fehmarn-Ausflug kombinieren"],
      website: "",
      address: "Burg auf Fehmarn",
      image: "/activities/schmetterlingspark.jpg",
    },
    {
      id: 38,
      slug: "schokoladen-manufaktur-marx-schwartbuck",
      title: "Schokoladen-Manufaktur Marx (Schwartbuck)",
      category: "Manufaktur",
      lat: 54.350,
      lng: 10.420,
      description:
        "Handgemachte Schokolade und feine Spezialitäten – ideal als Genuss-Stop oder Mitbringsel.",
      content:
        "Ein kleiner, feiner Ausflug für Genießer: regionale Manufaktur, besondere Sorten und perfekte Souvenirs.",
      tips: ["Mit Strand/Probstei kombinieren", "Souvenir einplanen", "Für Schoko-Fans Pflicht"],
      website: "",
      address: "Schwartbuck",
      image: "/activities/schokolade-marx.jpg",
    },
    {
      id: 39,
      slug: "schwentinetalfahrt",
      title: "Schwentinetalfahrt",
      category: "Natur & Schifffahrt",
      lat: 54.320,
      lng: 10.150,
      description:
        "Bootsfahrt durch das landschaftlich schöne Schwentinetal – ruhig, grün und perfekt zum Entschleunigen.",
      content:
        "Eine der entspanntesten Arten, die Natur in der Region zu erleben. Ideal als ruhiger Kontrast zu Strand und Stadt.",
      tips: ["Windschutz", "Ruhig unter der Woche", "Kamera/Handy"],
      website: "",
      address: "Region Kiel/Schwentine",
      image: "/activities/schwentine.jpg",
    },
    {
      id: 40,
      slug: "segway-tour-kiel",
      title: "Segway Tour Kiel",
      category: "Stadttour",
      lat: 54.323,
      lng: 10.122,
      description:
        "Geführte Segway-Touren durch Kiel – entspannt, informativ und mal was anderes.",
      content:
        "Ideal, wenn du Kiel in kurzer Zeit erkunden möchtest. Mit Guide bekommst du Highlights, Geschichte und schöne Spots.",
      tips: ["Vorab buchen", "Wetter checken", "Bequeme Kleidung"],
      website: "",
      address: "Kiel",
      image: "/activities/segway-kiel.jpg",
    },
    {
      id: 41,
      slug: "straussenfarm-ostseeblick-hohenfelde",
      title: "Straußenfarm Ostseeblick (Hohenfelde)",
      category: "Tierpark",
      lat: 54.369,
      lng: 10.504,
      description:
        "Strauße aus nächster Nähe erleben – mit Hofladen und spannenden Infos rund um die Tiere.",
      content:
        "Ein ungewöhnliches Ziel in der Region: Strauße sieht man nicht jeden Tag. Ideal für Familien und alle, die was Besonderes suchen.",
      tips: ["Mit Strandtag kombinieren", "Hofladen anschauen", "Für Kinder super"],
      website: "",
      address: "Hohenfelde",
      image: "/activities/straussenfarm.jpg",
    },
    {
      id: 42,
      slug: "tierpark-gettorf",
      title: "Tierpark Gettorf",
      category: "Zoo",
      lat: 54.406,
      lng: 9.973,
      description:
        "Großer Tierpark mit exotischen und heimischen Tieren, Tropenhalle und Streichelbereichen – Top für Familien.",
      content:
        "Der Tierpark Gettorf ist ein Klassiker für einen ganzen Tag. Viele Tiere, schöne Wege und oft Highlights wie Tropenhalle oder Streichelzoo.",
      tips: ["Zeit einplanen", "Futter/Highlights checken", "Für Kinderwagen geeignet"],
      website: "",
      address: "Gettorf",
      image: "/activities/tierpark-gettorf.jpg",
    },
    {
      id: 43,
      slug: "tolk-schau-freizeitpark",
      title: "Tolk-Schau Freizeitpark",
      category: "Freizeitpark",
      lat: 54.601,
      lng: 9.606,
      description:
        "Familien-Freizeitpark mit Fahrgeschäften und Shows – besonders beliebt bei Kindern.",
      content:
        "Die Tolk-Schau ist ein klassischer Familienpark – ideal für einen Tagesausflug mit Kids, wenn du Fahrgeschäfte und Unterhaltung suchst.",
      tips: ["Tickets/Öffnungszeiten prüfen", "Für Kids perfekt", "Bequeme Schuhe"],
      website: "",
      address: "Tolk",
      image: "/activities/tolk-schau.jpg",
    },
  ];
  